spec: flatmachine
spec_version: "1.0"
data:
  name: doc_processor
  states:
    initial:
      type: initial
      agent: reviewer.yml
      input:
        document: "{{ input.document }}"
        type: "processor for {{ input.name }}"
      output:
        result: "{{ output }}"
    final:
      type: final
      output: "{{ context.result }}"