spec: flatprofiles
spec_version: "0.8.0"

data:
  model_profiles:
    default:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 1.0
    creative:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 0.6
    fast:
      provider: cerebras
      name: zai-glm-4.7
      temperature: 1.0 

  default: default
